# Generated by Django 3.2.4 on 2021-06-12 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces', models.PositiveIntegerField(default=1)),
                ('machine', models.IntegerField(choices=[(2, 2)], default=2)),
                ('article', models.IntegerField(choices=[(17, '3ECJMCU2736000'), (18, '3EARACPE10CYII'), (19, '1EARACPLSA0000'), (20, '1EARACPLS50000'), (21, '1EARACPMS55000'), (22, '1EARACPMS57000'), (23, '3ECJMCP6327C00'), (24, '3ECJMCP6340C00'), (25, '1EARACPCSA0000'), (26, '1EARACPCS50000'), (27, '1EARACPCS70000'), (28, '3EARACPP432000'), (29, '3EARACPP443000'), (30, '3EARACPP454000'), (31, '3EARACPP465000'), (32, '3EARACPP486000'), (33, '3EARACPP1PRAGB'), (34, '3EARACPP1PRAG0'), (35, '3EARACPP1PRAGP'), (36, '3EARACPP1PRCYV'), (37, '3EARACPP1PR000'), (38, '3EARACPP2PA000'), (39, '3EARACPP2PR000'), (40, '3EARACPP2PG000'), (41, '3EARACPP3PA000'), (42, '3EARACPP3PACY0'), (43, '3EARACPP3P0000'), (44, '3EARACPP3PG000'), (45, '1EARACPPS55200'), (46, '1EARACPPS57200'), (47, '3EARACPJ100000'), (48, '3EARACPJ200000'), (49, '1EARACPJS50000'), (50, '1EARACPJS70000'), (51, '1EARACPTS55000'), (52, '1EARACPTS57000'), (53, '1EARACSPCV0000'), (54, '1EARACSTP00000'), (55, '1EARACSLBH0000')], default=1)),
                ('date_from', models.DateTimeField(default=datetime.datetime(2021, 6, 12, 19, 11, 56, 466306))),
                ('date_to', models.DateTimeField(default=datetime.datetime(2021, 6, 12, 20, 11, 56, 466306))),
            ],
        ),
        migrations.CreateModel(
            name='ProductionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=20)),
                ('machine', models.IntegerField()),
                ('pieces', models.IntegerField()),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
            ],
            options={
                'db_table': 'public.production_production',
            },
        ),
    ]
