# Generated by Django 3.2.4 on 2021-06-12 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 19, 12, 19, 906608)),
        ),
        migrations.AlterField(
            model_name='production',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 20, 12, 19, 906608)),
        ),
    ]
